version: '3.3'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - TZ=Asia/Bangkok
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - db_volume:/var/lib/mysql
      - ./Database/:/docker-entrypoint-initdb.d/
  backend:
    depends_on:
      - mysqldb
    image: img_backend
    container_name: backend
    build: ./Backend
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_PORT:$SPRING_PORT
    environment:
      - MYSQL_PATH=mysqldb
      - MYSQL_PORT=$MYSQL_PORT
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
  frontend:
    image: img_frontend
    container_name: frontend
    env_file: ./.env
    build: ./Frontend
    restart: unless-stopped
    volumes:
      - ./Frontend/:/var/local/app:cached
      - ./Frontend/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    ports:
      - $FRONT_PORT:$REVERSE
  proxy_nginx_frontend:
    image: nginx:1.19.1
    env_file: ./.env
    restart: unless-stopped
    volumes:
      - ./Frontend/config/nginx/Proxy.conf:/etc/nginx/conf.d/Proxy.conf:cached
      - ./Frontend/logs/nginx:/var/log/nginx:cached
    container_name: proxy_nginx_frontend
    ports:
      - $REVERSE:$REVERSE
    depends_on:
      - frontend
volumes:
  db_volume: {}
